name: Python Pipeline

on:
  # we want to trigger ci when someone push to master and create a pr
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buid:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # for now we just set it into 3.7
        python-version: [3.7]

    steps:
    - name: Checkout Code
      uses: actions/checkout@master
      with:
        # so it can fetch current tagged version
        fetch-depth: '0'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{matrix.python-version}}

    - name: Install CI Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.ci.txt
        pip install wheel

    - name: Static Checking
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --max-complexity=10

    - name: Static Analysis
      run: |
        make check-cc
        make check-mi
        make check-raw
        make check-hal

    - name: Unit Testing + Coverage
      run: |
        make check-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Build Package distribution
      run: |
        make build

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
